# Generated by Django 3.2.10 on 2022-01-04 18:38

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('solaris', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablecolumn',
            old_name='page',
            new_name='table',
        ),
        migrations.RenameField(
            model_name='tablerow',
            old_name='page',
            new_name='table',
        ),
        migrations.AlterField(
            model_name='list',
            name='content',
            field=django_jsonform.models.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, default=list, size=None),
        ),
    ]
