# Generated by Django 3.2.10 on 2022-01-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solaris', '0003_tablecell_spanned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablerow',
            name='table',
        ),
        migrations.AlterField(
            model_name='tablecell',
            name='column',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tablecell',
            name='row',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='TableColumn',
        ),
        migrations.DeleteModel(
            name='TableRow',
        ),
    ]
