# Generated by Django 3.2.10 on 2022-01-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solaris', '0004_auto_20220105_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='columns',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='table',
            name='rows',
            field=models.IntegerField(default=0),
        ),
    ]
