# Generated by Django 3.2.10 on 2022-01-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solaris', '0005_auto_20220105_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
