# Generated by Django 3.2.11 on 2022-01-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solaris', '0006_alter_header_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tablecell',
            options={'ordering': ['row', 'column']},
        ),
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
